Implement POST endpoint
Progress-House/ofitoo-backend pull request #6
Opened 2024-02-27 21:27 UTC by DawidStuzynski

2024-02-29 11:44 UTC, McBlankenburg commented on microservices/product/src/main/java/com/ofitoo/microservices/product/controller/ProductController.java
> +    public ResponseEntity<ProductDto> addProduct(@RequestBody final CreateProductDto createProductDto, @RequestHeader("ownerId") Long ownerId) {
I'm not sure if it should be called ownerId, maybe it's better to call it as userId and later when assigning it to ownerId in ProductService, it will be known where it came from? 

`Long UserId = ownerID;`

+ I'm not sure if we'll keep it as Long in user-service, I'd rather go for UUID2

but of course, this will be for the next tasks once the user-service has some basic structure

Later, we will need to create security in API Gateway to reject the ownerId (userId) header passed in the request from the client application so that the user is sometimes unable to replace the userId even if the user-service does not find any userId/OwnerId

2024-02-29 11:47 UTC, McBlankenburg commented on microservices/product/src/main/java/com/ofitoo/microservices/product/controller/ProductController.java
> +    public ResponseEntity<ProductDto> addProduct(@RequestBody final CreateProductDto createProductDto, @RequestHeader("ownerId") Long ownerId) {
does this have to be the final field? 
`final CreateProductDto createProductDto`
it record so it shouldn't be mutable right?

2024-02-29 11:53 UTC, McBlankenburg requested changes

2024-02-29 11:53 UTC, McBlankenburg commented on microservices/product/src/main/java/com/ofitoo/microservices/product/controller/ProductController.java
> +        final var product = productService.addProduct(createProductDto, ownerId);
I'm not sure if we should allow vars in this situation.
everything works fine, but it is not known what object is returned here. In theory, you can guess, but it slightly reduces readability,
In below situation we know "something" variable is object because we see it on the right side.
`var something = new Object();`

but here i don't know what type is here.
`final var product = productService.addProduct(createProductDto, ownerId);`

I checked it and it turned out that it is ProductDto which one is record, as above, do we have to write final if it is immutable?

2024-02-29 11:56 UTC, McBlankenburg commented on microservices/product/src/main/java/com/ofitoo/microservices/product/ProductApplication.java
>      public static void main(String[] args) {
Java 21 greatly simplifies the way we can write a simple program:

```
void main() {
    System.out.println("Hello, World!");
}
```

source:
https://www.baeldung.com/java-21-unnamed-class-instance-main

2024-02-29 11:57 UTC, McBlankenburg commented on microservices/product/src/main/java/com/ofitoo/microservices/product/mapper/ProductMapper.java
> +    public ProductEntity toEntity(final CreateProductDto createProductDto, final Long ownerId) {
it should be final if it Dto (record) ?
`final CreateProductDto createProductDto`

2024-02-29 11:59 UTC, McBlankenburg commented on microservices/product/src/main/java/com/ofitoo/microservices/product/service/ProductService.java
> +    public ProductDto addProduct(final CreateProductDto createProductDto, final Long ownerId) {
as above

2024-02-29 12:01 UTC, McBlankenburg commented on microservices/product/src/main/java/com/ofitoo/microservices/product/service/ProductService.java
> +        final var product = productMapper.toEntity(createProductDto, ownerId);
idk what is there, that Product it DTO or ProductEntity, same below in savedEntity

2024-02-29 12:02 UTC, McBlankenburg commented on microservices/product/src/test/java/com/ofitoo/microservices/product/mapper/ProductMapperTest.java
> +    void shoudMakeGowno() {
xD gowno what it mean ? 👯

2024-02-29 12:09 UTC, McBlankenburg requested changes

2024-02-29 12:09 UTC, McBlankenburg commented on microservices/product/src/test/java/com/ofitoo/microservices/product/mapper/ProductMapperTest.java
> +import static org.junit.jupiter.api.Assertions.*;
we should single import here, but maybe we will do it by "code style" later

2024-02-29 12:09 UTC, McBlankenburg commented on microservices/product/pom.xml
> +        </dependency><dependency>
</dependency><dependency> is it in one line ? maybe \n

2024-02-29 20:18 UTC, DawidStuzynski commented on microservices/product/src/main/java/com/ofitoo/microservices/product/mapper/ProductMapper.java
> +    public ProductEntity toEntity(final CreateProductDto createProductDto, final Long ownerId) {
We should align to some convention, in kotlin argument method works this way, so you can override them

2024-02-29 20:19 UTC, DawidStuzynski commented on microservices/product/src/main/java/com/ofitoo/microservices/product/service/ProductService.java
> +        final var product = productMapper.toEntity(createProductDto, ownerId);
I will change it to not use var if it is not very readeable

2024-02-29 20:20 UTC, DawidStuzynski commented on microservices/product/src/test/java/com/ofitoo/microservices/product/mapper/ProductMapperTest.java
> +        assertAll("messssage",
some leftover after out discustion, probably we have to also talk about proper assertions because now I can't what argument was not proper in assertion

2024-02-29 20:21 UTC, DawidStuzynski commented on microservices/product/src/test/java/com/ofitoo/microservices/product/mapper/ProductMapperTest.java
> +import static org.junit.jupiter.api.Assertions.*;
definitely, we should avoid * in any imports

2024-03-06 18:41 UTC, McBlankenburg requested changes

2024-03-06 18:41 UTC, McBlankenburg commented on microservices/product/src/main/java/com/ofitoo/microservices/product/controller/ProductController.java
> +    @PostMapping(consumes = APPLICATION_JSON_VALUE, produces = APPLICATION_JSON_VALUE)
if we only use json in the entire application, we can remove consumes and produces from @PostMapping and instead add this configuration to application.yml

![image](https://github.com/Progress-House/ofitoo-backend/assets/58309339/7e40fe8b-e05f-434d-9c22-f74a91502c4b)

2024-03-06 18:41 UTC, McBlankenburg commented on microservices/product/src/test/java/com/ofitoo/microservices/product/integration/ProductIntegrationTest.java
> +    public void ProductController$createProductShouldCreateProductInDatabaseAndReturnIt() {
shouldCreateProductInDatabaseAndReturnIt()

2024-03-06 18:41 UTC, McBlankenburg commented on microservices/product/src/test/java/com/ofitoo/microservices/product/integration/ProductIntegrationTest.java
> +                .header(CONTENT_TYPE, APPLICATION_JSON_VALUE)
after adding the json-related configuration to application.yml, it will probably no longer be needed.

2024-03-06 18:41 UTC, McBlankenburg commented on microservices/product/src/test/java/com/ofitoo/microservices/product/mapper/ProductMapperTest.java
> +    void ProductMapper$toEntityShouldMapCreateProductDtoToProductEntity() {
shouldMapCreateProductDtoToProductEntity()

2024-03-06 18:41 UTC, McBlankenburg commented on microservices/product/src/test/java/com/ofitoo/microservices/product/mapper/ProductMapperTest.java
> +    void ProductMapper$toDtoShouldMapProductEntityToProductDto() {
shouldMapProductEntityToProductDto()

2024-03-06 18:41 UTC, McBlankenburg commented on microservices/product/src/test/java/com/ofitoo/microservices/product/model/ProductDtoModel.java
> +abstract public class ProductDtoModel {
please change the name to something more meaningful that it is only used for tests, for example, ProductDtoModelTestUtil

2024-03-06 18:41 UTC, McBlankenburg commented on microservices/product/src/test/java/com/ofitoo/microservices/product/model/ProductEntityModel.java
> +abstract public class ProductEntityModel {
please change the name to something more meaningful that it is only used for tests, for example, ProductEntityModelTestUtil

2024-03-06 18:41 UTC, McBlankenburg commented on scripts/docker-compose.yml
> +
please add a comment about the fact that under port 8081 you should enter credentiale, admin: admin, password: pass

2024-03-07 17:34 UTC, merged